server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource_admin
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
